#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_SENSOR=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
# CONFIG_UART_NRFX_CUSTOM_BAUDRATE=y

CONFIG_OVERRIDE_FRAME_POINTER_DEFAULT=y
CONFIG_OMIT_FRAME_POINTER=n
CONFIG_EXTRA_EXCEPTION_INFO=y
CONFIG_HW_STACK_PROTECTION=y
# CONFIG_DEBUG=y
# CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_THREAD_MONITOR=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_INIT_STACKS=n
CONFIG_RESET_ON_FATAL_ERROR=n

CONFIG_UART_ASYNC_API=y

CONFIG_REBOOT=y
CONFIG_RAM_POWER_DOWN_LIBRARY=y
CONFIG_SETTINGS=y
CONFIG_REGULATOR=y

CONFIG_BOOTLOADER_MCUBOOT=y

CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_PARTITION=y
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_THREADS=y
CONFIG_DEBUG_COREDUMP_THREADS_METADATA=y

CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=y

CONFIG_HWINFO=y

CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
# CONFIG_THREAD_LOCAL_STORAGE=y
