#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_USE_MODULE=n #tell Zephyr not to build picolib from module, toolchain should provide it
CONFIG_CPP=y
CONFIG_STD_CPP26=y

# CONFIG_LLVM_USE_LLD=y
# CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

