# Enable Memfault
CONFIG_MEMFAULT=y

# Use internal flash to store the coredump
CONFIG_MEMFAULT_COREDUMP_STORAGE_NRF_RRAM=y
CONFIG_MEMFAULT_COREDUMP_FULL_THREAD_STACKS=y
CONFIG_MEMFAULT_SOFTWARE_WATCHDOG_TIMEOUT_SECS=5
CONFIG_MEMFAULT_PERIODIC_UPLOAD=n
# set a dummy project key; this setting is required by the nrf-connect
# integration, but it is unused in a non-HTTP application
CONFIG_MEMFAULT_NCS_PROJECT_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Set device information fields
CONFIG_MEMFAULT_NCS_DEVICE_ID_RUNTIME=y
CONFIG_MEMFAULT_NCS_HW_VERSION="a"
CONFIG_MEMFAULT_NCS_FW_TYPE="nrf54l15_zb"
CONFIG_MEMFAULT_NCS_FW_VERSION_STATIC=y
